default:
    @just --list --unsorted

tool := "ansible-example"
docker_image_version := "0.0.2"
docker_image := tool + ":" + docker_image_version

build:
    docker build --no-cache -t {{docker_image}} .

debug:
    touch ~/.docker_history
    docker run -t --rm -v $PWD/../:/src -v /tmp:/tmp -v ~/.docker_history:/root/.docker_history -e ANSIBLE_PORT=2222 -e HISTFILE=/root/.docker_history -v $(realpath ../ssh_server/keys):/root/.ssh -v $(mktemp -d):/root/.ansible --network host {{docker_image}} /bin/bash -c "tmate"

run:
    touch ~/.docker_history
    docker run -t --rm -v $PWD/../:/src -v /tmp:/tmp -v ~/.docker_history:/root/.docker_history -e ANSIBLE_PORT=2222 -e HISTFILE=/root/.docker_history -v $(realpath ../ssh_server/keys):/root/.ssh -v $(mktemp -d):/root/.ansible --network host {{docker_image}} /bin/bash -c "cd ansible_client/ && ansible-playbook -i hosts -e \"ansible_port=2222\" site.yml"
