FROM arm64v8/debian

MAINTAINER mihaigalos

RUN apt-get update \
    &&  apt-get -qy install \
	curl ca-certificates \
	python3 python3-pip \
        python3-dev git \
	gcc make \
	i2c-tools \
    sudo vim zsh \
    &&  apt-get -y autoremove \
    &&  apt-get -y clean \
    &&  apt-get -y purge \
    &&  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \ 

RUN pip3 install rpi.gpio

CMD ["/bin/bash"]
